spring:
  application:
    name: book-store-front-A

  profiles:
    active: dev

  # HTML form 에서 GET, POST 뿐 아니라 PUT, DELETE 도 사용하기 위해서 설정
  mvc:
    hidden method:
      filter:
        enabled: true

logging:
  file:
    path: ./logs

  level:
    com.netflix.discovery: ERROR
    com.netflix.eureka: ERROR

oritang:
  redis:
    host: 4c4a07c6d57c41cba23cf12de6c87559
    port: 0de6a31493de4282830c2dab83e7264c
    password: d9b767e1131b4434b75d1fb52444ee1e
    database: 3ba42db5dac041a391c6fa993222ec66
