spring:

  # 라이브 리로드 활성화
  devtools:
    livereload:
      enabled: true

  # 캐시 비활성화
  thymeleaf:
    cache: false

server:
  port: 8081

payco:
  client-id: 3RD5T_6SsRZZqiV8oXgma4_
  client-secret: h6eMk6FBKULyudzmTDlkvyLI
  redirect-uri: http://local.host.com:8081/auth/payco/callback