name: CD to Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean package

      - name: Copy files via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_ID }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "target/*.jar"
          target: "/home/${{ secrets.SSH_ID }}/"
          rm: false
          timeout: '30s'
          command_timeout: '10m'
          use_insecure_cipher: false
          debug: true

      - name: Deploy to Server
        env:
          SSH_IP: ${{ secrets.SSH_IP }}
          SSH_ID: ${{ secrets.SSH_ID }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          PORT1: ${{ secrets.PORT1 }}
          PORT2: ${{ secrets.PORT2 }}
        run: |
          ssh -i ssh_key -o StrictHostKeyChecking=no $SSH_ID@$SSH_IP << 'EOF'
          if pgrep -f "java -jar /home/$SSH_ID/your-app.jar --server.port=$PORT1"; then
            pkill -f "java -jar /home/$SSH_ID/your-app.jar --server.port=$PORT1"
          fi
          if pgrep -f "java -jar /home/$SSH_ID/your-app.jar --server.port=$PORT2"; then
            pkill -f "java -jar /home/$SSH_ID/your-app.jar --server.port=$PORT2"
          fi
          nohup java -jar /home/$SSH_ID/your-app.jar --server.port=$PORT1 > app1.log 2>&1 &
          nohup java -jar /home/$SSH_ID/your-app.jar --server.port=$PORT2 > app2.log 2>&1 &
          EOF
