name: CD to Ubuntu Server #

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean package

      - name: Copy files via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_ID }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{secrets.SSH_PORT}}
          source: "target/*.jar"
          target: "~/"
          rm: false
          timeout: '30s'
          command_timeout: '10m'
          use_insecure_cipher: false
          debug: true

#      - name: Deploy to Server
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.SSH_IP }}
#          username: ${{ secrets.SSH_ID }}
#          key: ${{ secrets.SSH_KEY }}
#          port: ${{secrets.SSH_PORT}}
#          script: |
#            if pgrep -f "java -jar ~/target/BOOK-STORE-FRONT.jar --server.port=${{secrets.FRONT_PORT_A}}"; then
#              pkill -f "java -jar ~/target/BOOK-STORE-FRONT.jar --server.port=${{secrets.FRONT_PORT_A}}"
#            fi
#            nohup java -jar ~/target/BOOK-STORE-FRONT.jar --server.port=${{ secrets.FRONT_PORT_A }} > app.log 2>&1 &
#            if pgrep -f "java -jar ~/target/BOOK-STORE-FRONT.jar --server.port=${{secrets.FRONT_PORT_B}}"; then
#              pkill -f "java -jar ~/target/BOOK-STORE-FRONT.jar --server.port=${{secrets.FRONT_PORT_B}}"
#            fi
#            nohup java -jar ~/target/BOOK-STORE-FRONT.jar --server.port=${{ secrets.FRONT_PORT_B }} > app.log 2>&1 &
#


      # 앱 포트로 실행된 jar 파일 종료
      - name: Stop existing Spring Boot application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_ID }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo "Stopping existing application..."
            pid=$(lsof -t -i:${{ secrets.FRONT_PORT_A }}) && kill -9 $pid || echo "No application running on port ${{ secrets.FRONT_PORT_A }}"

      #앱 포트로 배포 한 jar 파일 실행
      - name: execute shell script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_ID }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script_stop: true
          script: |
            echo "Starting new application..."
            nohup java -jar ~/target/BOOK-STORE-FRONT.jar --server.port=${{ secrets.FRONT_PORT_A }} > app.log 2>&1 &
            echo "New application started. Check app.log for details."