name: Continuous Deployment

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # jar 파일 배포
      - name: upload file
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_ID }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "target/BOOK-STORE-FRONT.jar"
          target: "~/"
          rm: false

      # 앱 포트로 실행된 jar 파일 종료
      - name: Stop existing Spring Boot application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_ID }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo "Stopping existing application..."
            pid=$(lsof -t -i:${{ secrets.FRONT_PORT_A }}) && kill -9 $pid || echo "No application running on port ${{ secrets.FRONT_PORT_A }}"

      #앱 포트로 배포 한 jar 파일 실행
      - name: execute shell script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_ID }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script_stop: true
          script: |
            echo "Starting new application..."
            nohup java -jar ~/target/BOOK-STORE-FRONT.jar --server.port=${{ secrets.FRONT_PORT_A }} > app.log 2>&1 &
            echo "New application started. Check app.log for details."

